ALTER SEQUENCE "public"."dm_entity_id_seq" OWNED BY NONE;
CREATE SEQUENCE "public"."repository_id_seq" INCREMENT 1 START 1 MAXVALUE 9223372036854775807 MINVALUE 1 CACHE 1;
ALTER SEQUENCE "public"."rule_id_seq" OWNED BY NONE;
DROP SEQUENCE "public"."doc_type_id_seq" CASCADE;
CREATE TABLE "public"."authenticated_services" ("service_id" varchar(255) NOT NULL,"service_key" varchar(255) NOT NULL,CONSTRAINT "authenticated_services_pkey" PRIMARY KEY ("service_id") NOT DEFERRABLE INITIALLY IMMEDIATE) WITH (OIDS=FALSE);
ALTER TABLE "public"."data_transaction" DROP CONSTRAINT "quotero_data_transaction_document_version_fk" CASCADE;
ALTER TABLE "public"."data_transaction" DROP CONSTRAINT "quotero_data_transaction_authentication_source_fk" CASCADE;
ALTER TABLE "public"."dm_entity_acl" DROP CONSTRAINT "dm_entity_acl_hash_fk" CASCADE;
ALTER TABLE "public"."dm_entity_acl" DROP CONSTRAINT "dm_entity_acl_dm_entity_id_fk" CASCADE;
ALTER TABLE "public"."dm_entity_attributes" DROP CONSTRAINT "ent_attr_entity_fk" CASCADE;
ALTER TABLE "public"."document" DROP CONSTRAINT "quotero_document_fk" CASCADE;
ALTER TABLE "public"."checkout" DROP CONSTRAINT "quotero_checkout_fk" CASCADE;
ALTER TABLE "public"."checkout" DROP CONSTRAINT "quotero_checkout_fk1" CASCADE;
ALTER TABLE "public"."document_comment" DROP CONSTRAINT "quotero_document_comment_document_version_fk" CASCADE;
ALTER TABLE "public"."document_comment" DROP CONSTRAINT "quotero_document_comment_author_source_fkey" CASCADE;
ALTER TABLE "public"."document_type" DROP CONSTRAINT "quotero_document_type_fk" CASCADE;
ALTER TABLE "public"."document_version" DROP CONSTRAINT "dt_id_fk" CASCADE;
ALTER TABLE "public"."document_version" DROP CONSTRAINT "quotero_document_version_fk" CASCADE;
ALTER TABLE "public"."document_version" DROP CONSTRAINT "quotero_document_version_fk1" CASCADE;
ALTER TABLE "public"."document_workflow_status" DROP CONSTRAINT "quotero_document_workflow_status_workflow_status_uid_fkey" CASCADE;
ALTER TABLE "public"."document_workflow_status" DROP CONSTRAINT "quotero_document_worklow_status_document_fk" CASCADE;
ALTER TABLE "public"."document_workflow_status_request" DROP CONSTRAINT "quotero_document_workflow_status_reque_workflow_status_uid_fkey" CASCADE;
ALTER TABLE "public"."document_workflow_status_request" DROP CONSTRAINT "quotero_document_workflow_request_document_uid_fk" CASCADE;
ALTER TABLE "public"."document_workflow_status_request" DROP CONSTRAINT "quotero_document_workflow_status_request_fk5" CASCADE;
ALTER TABLE "public"."document_workflow_status_request" DROP CONSTRAINT "quotero_document_workflow_status_request_user_source_fkey" CASCADE;
ALTER TABLE "public"."entity_log" DROP CONSTRAINT "quotero__workspace_log_fk" CASCADE;
ALTER TABLE "public"."generic_log" DROP CONSTRAINT "quotero_log_fk" CASCADE;
ALTER TABLE "public"."groups" DROP CONSTRAINT "quotero_group_fk" CASCADE;
ALTER TABLE "public"."meta" DROP CONSTRAINT "meta_dt_id_fk" CASCADE;
ALTER TABLE "public"."meta" DROP CONSTRAINT "quotero_meta_fk1" CASCADE;
ALTER TABLE "public"."meta_boolean_value" DROP CONSTRAINT "quotero_meta_boolean_value_meta_uid_fkey" CASCADE;
ALTER TABLE "public"."meta_boolean_value" DROP CONSTRAINT "quotero_metabool_doc_version_fk" CASCADE;
ALTER TABLE "public"."meta_number_value" DROP CONSTRAINT "quotero_meta_number_value_meta_uid_fkey" CASCADE;
ALTER TABLE "public"."meta_number_value" DROP CONSTRAINT "quotero_metanum_doc_version_fk" CASCADE;
ALTER TABLE "public"."meta_string_value" DROP CONSTRAINT "quotero_meta_string_value_meta_uid_fkey" CASCADE;
ALTER TABLE "public"."meta_string_value" DROP CONSTRAINT "quotero_metastring_doc_version_fk" CASCADE;
ALTER TABLE "public"."roles" DROP CONSTRAINT "quotero_role_fk" CASCADE;
ALTER TABLE "public"."rule_event" DROP CONSTRAINT "quotero_rule_event_rule_id_fk" CASCADE;
ALTER TABLE "public"."rule_param" DROP CONSTRAINT "quotero_rule_param_rule_fk" CASCADE;
ALTER TABLE "public"."user_attributes" DROP CONSTRAINT "user_attributes_user_fk" CASCADE;
ALTER TABLE "public"."user_group" DROP CONSTRAINT "quotero_user_group_fk2" CASCADE;
ALTER TABLE "public"."user_session" DROP CONSTRAINT "quotero_session_fk" CASCADE;
ALTER TABLE "public"."users" DROP CONSTRAINT "quotero_user_fk" CASCADE;
ALTER TABLE "public"."workflow_status" DROP CONSTRAINT "quotero_workflow_status_fk1" CASCADE;
ALTER TABLE "public"."workflow_status" DROP CONSTRAINT "quotero_workflow_status_fk" CASCADE;
ALTER TABLE "public"."workflow_status_manager" DROP CONSTRAINT "quotero_workflow_status_manager_workflow_fkey2" CASCADE;
ALTER TABLE "public"."workflow_status_manager" DROP CONSTRAINT "quotero_workflow_status_manager_fkey1" CASCADE;
ALTER TABLE "public"."authentication_params" DROP CONSTRAINT "quotero_authentication_params_fkey" CASCADE;
ALTER TABLE "public"."enumeration_value" DROP CONSTRAINT "quotero_enumeration_value_fk" CASCADE;
ALTER TABLE "public"."meta_date_value" DROP CONSTRAINT "quotero_meta_date_value_meta_uid_fkey" CASCADE;
ALTER TABLE "public"."meta_date_value" DROP CONSTRAINT "quotero_metadate_doc_version_fk" CASCADE;
ALTER TABLE "public"."data_transaction" DROP CONSTRAINT "quotero_data_transaction_pk" CASCADE;
ALTER TABLE "public"."dm_entity_acl" DROP CONSTRAINT "dm_entity_acl_pk" CASCADE;
ALTER TABLE "public"."dm_entity_attributes" DROP CONSTRAINT "entity_attr_pk" CASCADE;
ALTER TABLE "public"."document" DROP CONSTRAINT "quotero_document_pkey" CASCADE;
ALTER TABLE "public"."document" DROP CONSTRAINT "q_dm_entity_uid" CASCADE;
ALTER TABLE "public"."checkout" DROP CONSTRAINT "quotero_checkout_idx" CASCADE;
ALTER TABLE "public"."document_comment" DROP CONSTRAINT "quotero_document_comment_pkey" CASCADE;
ALTER TABLE "public"."document_type" DROP CONSTRAINT "quotero_document_type_pkey" CASCADE;
ALTER TABLE "public"."document_version" DROP CONSTRAINT "quotero_document_version_pkey" CASCADE;
ALTER TABLE "public"."document_workflow_status" DROP CONSTRAINT "quotero_document_workflow_status_pk" CASCADE;
ALTER TABLE "public"."document_workflow_status_request" DROP CONSTRAINT "quotero_document_workflow_status_request_pkey" CASCADE;
ALTER TABLE "public"."entity_log" DROP CONSTRAINT "quotero_workspace_log_pkey" CASCADE;
ALTER TABLE "public"."folder" DROP CONSTRAINT "quotero_folder_pkey" CASCADE;
ALTER TABLE "public"."folder" DROP CONSTRAINT "q_dm_entity_id" CASCADE;
ALTER TABLE "public"."generic_log" DROP CONSTRAINT "quotero_log_pkey" CASCADE;
ALTER TABLE "public"."groups" DROP CONSTRAINT "quotero_group_pk" CASCADE;
ALTER TABLE "public"."meta" DROP CONSTRAINT "quotero_meta_pkey" CASCADE;
ALTER TABLE "public"."meta_boolean_value" DROP CONSTRAINT "quotero_meta_boolean_value_pkey" CASCADE;
ALTER TABLE "public"."meta_date_value" DROP CONSTRAINT "quotero_meta_date_value_pkey" CASCADE;
ALTER TABLE "public"."meta_number_value" DROP CONSTRAINT "quotero_meta_number_value_pkey" CASCADE;
ALTER TABLE "public"."meta_string_value" DROP CONSTRAINT "quotero_meta_string_value_document_uid_pkey" CASCADE;
ALTER TABLE "public"."related_documents" DROP CONSTRAINT "quotero_related_documetns_pk" CASCADE;
ALTER TABLE "public"."roles" DROP CONSTRAINT "quotero_role_idx" CASCADE;
ALTER TABLE "public"."rule_event" DROP CONSTRAINT "quotero_rule_event_pk" CASCADE;
ALTER TABLE "public"."rule_exclude_paths" DROP CONSTRAINT "rule_excl_path" CASCADE;
ALTER TABLE "public"."rule_exclude_paths" DROP CONSTRAINT "rules_excl_path" CASCADE;
ALTER TABLE "public"."rule_param" DROP CONSTRAINT "quotero_rule_param_pk" CASCADE;
ALTER TABLE "public"."rules" DROP CONSTRAINT "quotero_rule_id" CASCADE;
ALTER TABLE "public"."user_attributes" DROP CONSTRAINT "user_attributes_pk" CASCADE;
ALTER TABLE "public"."user_group" DROP CONSTRAINT "quotero_user_group_idx" CASCADE;
ALTER TABLE "public"."user_session" DROP CONSTRAINT "quotero_session_pkey" CASCADE;
ALTER TABLE "public"."users" DROP CONSTRAINT "quotero_user_pk" CASCADE;
ALTER TABLE "public"."workflow" DROP CONSTRAINT "quotero_workflow_pkey" CASCADE;
ALTER TABLE "public"."workflow_status" DROP CONSTRAINT "quotero_workflow_status_pkey" CASCADE;
ALTER TABLE "public"."workflow_status_manager" DROP CONSTRAINT "quotero_workflow_status_manager_pkey" CASCADE;
ALTER TABLE "public"."workspace" DROP CONSTRAINT "quotero_workspace_pkey" CASCADE;
ALTER TABLE "public"."workspace" DROP CONSTRAINT "q_dm_entity_id" CASCADE;
ALTER TABLE "public"."authentication_params" DROP CONSTRAINT "quotero_authentication_params_pkey" CASCADE;
ALTER TABLE "public"."authentication_source" DROP CONSTRAINT "quotero_authentication_source_pkey" CASCADE;
ALTER TABLE "public"."bookmarks" DROP CONSTRAINT "quotero_bookmark_pk" CASCADE;
ALTER TABLE "public"."dm_entity" DROP CONSTRAINT "quotero_dm_entity_unique_path" CASCADE;
ALTER TABLE "public"."dm_entity" DROP CONSTRAINT "dm_entity_uid_pk" CASCADE;
ALTER TABLE "public"."dm_security_rules" DROP CONSTRAINT "quotero_dm_security_rules_security_entity_type_key" CASCADE;
ALTER TABLE "public"."dm_security_rules" DROP CONSTRAINT "quotero_dm_security_rules_pkey" CASCADE;
ALTER TABLE "public"."enumeration_value" DROP CONSTRAINT "quotero_enumeration_value_pk" CASCADE;
ALTER TABLE "public"."meta_feed" DROP CONSTRAINT "meta_feed_pkey" CASCADE;
DROP VIEW "public"."document_pojo" CASCADE;
ALTER TABLE "public"."authentication_params" ALTER COLUMN "authentication_source_name" TYPE varchar(255);
ALTER TABLE "public"."authentication_source" ALTER COLUMN "source_name" TYPE varchar(255);
ALTER TABLE "public"."authentication_source" ALTER COLUMN "java_class" SET NOT NULL;
ALTER TABLE "public"."bookmarks" ALTER COLUMN "bk_owner" TYPE varchar(255);
ALTER TABLE "public"."bookmarks" ALTER COLUMN "bk_owner_source" TYPE varchar(255);
ALTER TABLE "public"."bookmarks" ALTER COLUMN "dm_entity_type" TYPE int4, ALTER COLUMN "dm_entity_type" DROP NOT NULL;
ALTER TABLE "public"."checkout" ALTER COLUMN "checkout_date" SET NOT NULL;
ALTER TABLE "public"."checkout" ALTER COLUMN "username" TYPE varchar(255);
ALTER TABLE "public"."checkout" ALTER COLUMN "user_source" TYPE varchar(255), ALTER COLUMN "user_source" SET NOT NULL;
ALTER TABLE "public"."data_transaction" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "public"."data_transaction" ALTER COLUMN "data_size" DROP NOT NULL;
ALTER TABLE "public"."data_transaction" ALTER COLUMN "file_path" TYPE varchar(2000);
ALTER TABLE "public"."data_transaction" ALTER COLUMN "has_been_chk_out" SET NOT NULL;
ALTER TABLE "public"."data_transaction" ALTER COLUMN "hash_md5" DROP NOT NULL;
ALTER TABLE "public"."data_transaction" ALTER COLUMN "hash_sha" DROP NOT NULL;
ALTER TABLE "public"."data_transaction" ALTER COLUMN "last_activity_date" DROP NOT NULL;
ALTER TABLE "public"."data_transaction" ALTER COLUMN "username" TYPE varchar(255);
ALTER TABLE "public"."data_transaction" ALTER COLUMN "user_source" TYPE varchar(255);
ALTER TABLE "public"."dm_entity" ALTER COLUMN "dm_entity_id" DROP DEFAULT;
ALTER TABLE "public"."dm_entity" ALTER COLUMN "creation_date" SET NOT NULL;
ALTER TABLE "public"."dm_entity" ALTER COLUMN "dm_entity_name" SET NOT NULL;
ALTER TABLE "public"."dm_entity" ALTER COLUMN "dm_entity_owner" TYPE varchar(255),ALTER COLUMN "dm_entity_owner" SET NOT NULL;
ALTER TABLE "public"."dm_entity" ALTER COLUMN "dm_entity_owner_source" TYPE varchar(255),ALTER COLUMN "dm_entity_owner_source" SET NOT NULL;
ALTER TABLE "public"."dm_entity" ALTER COLUMN "update_date" SET NOT NULL;
ALTER TABLE "public"."dm_entity_acl" ALTER COLUMN "rule_hash" TYPE varchar(255);
ALTER TABLE "public"."dm_entity_acl" ALTER COLUMN "dm_entity_type" DROP NOT NULL;
ALTER TABLE "public"."dm_entity_attributes" ALTER COLUMN "is_indexed" SET NOT NULL;
ALTER TABLE "public"."dm_entity_attributes" ADD COLUMN "attribute_name_dbl" varchar(255) NOT NULL;
ALTER TABLE "public"."dm_entity_attributes" ALTER COLUMN "attribute_value" TYPE varchar(255);
ALTER TABLE "public"."dm_entity_attributes" ALTER COLUMN "attribute_name" TYPE varchar(255);
ALTER TABLE "public"."dm_security_rules" ALTER COLUMN "security_entity_source" TYPE varchar(255);
ALTER TABLE "public"."dm_security_rules" ALTER COLUMN "security_entity_id" TYPE varchar(255);
ALTER TABLE "public"."document" ALTER COLUMN "extension" TYPE varchar(255);
ALTER TABLE "public"."document" ALTER COLUMN "folder_id" SET NOT NULL;
ALTER TABLE "public"."document" ALTER COLUMN "mime_type" TYPE varchar(255);
ALTER TABLE "public"."document_comment" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "public"."document_comment" ALTER COLUMN "author_name" TYPE varchar(255),ALTER COLUMN "author_name" SET NOT NULL;
ALTER TABLE "public"."document_comment" ALTER COLUMN "author_source" TYPE varchar(255),ALTER COLUMN "author_source" SET NOT NULL;
ALTER TABLE "public"."document_comment" ALTER COLUMN "comment_content" SET NOT NULL;
ALTER TABLE "public"."document_comment" ALTER COLUMN "comment_date" SET NOT NULL;
ALTER TABLE "public"."document_comment" ALTER COLUMN "document_version_id" SET NOT NULL;
ALTER TABLE "public"."document_type" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "public"."document_type" ALTER COLUMN "type_name" TYPE varchar(200),ALTER COLUMN "type_name" SET NOT NULL;
ALTER TABLE "public"."document_version" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "public"."document_version" ALTER COLUMN "author" TYPE varchar(255),ALTER COLUMN "author" SET NOT NULL;
ALTER TABLE "public"."document_version" ALTER COLUMN "author_source" TYPE varchar(255),ALTER COLUMN "author_source" SET NOT NULL;
ALTER TABLE "public"."document_version" ALTER COLUMN "creation_date" SET NOT NULL;
ALTER TABLE "public"."document_version" ALTER COLUMN "modification_date" SET NOT NULL;
ALTER TABLE "public"."document_version" ALTER COLUMN "storage_path" SET NOT NULL;
ALTER TABLE "public"."document_workflow_status" ALTER COLUMN "security_entity_name" TYPE varchar(255),ALTER COLUMN "security_entity_name" SET NOT NULL;
ALTER TABLE "public"."document_workflow_status" ALTER COLUMN "security_entity_source" TYPE varchar(255),ALTER COLUMN "security_entity_source" SET NOT NULL;
ALTER TABLE "public"."document_workflow_status" ALTER COLUMN "status_date" SET NOT NULL;
ALTER TABLE "public"."document_workflow_status_request" ALTER COLUMN "username" TYPE varchar(255);
ALTER TABLE "public"."document_workflow_status_request" ALTER COLUMN "user_source" TYPE varchar(255);
ALTER TABLE "public"."document_workflow_status_request" ALTER COLUMN "request_status" DROP NOT NULL;
ALTER TABLE "public"."document_workflow_status_request" ALTER COLUMN "request_comment" TYPE varchar(255);
ALTER TABLE "public"."document_workflow_status_request" ALTER COLUMN "validator_user_name" TYPE varchar(255);
ALTER TABLE "public"."document_workflow_status_request" ALTER COLUMN "validator_user_source" TYPE varchar(255);
ALTER TABLE "public"."entity_log" ALTER COLUMN "action" DROP NOT NULL;
ALTER TABLE "public"."entity_log" ALTER COLUMN "log_time" SET NOT NULL;
ALTER TABLE "public"."entity_log" ALTER COLUMN "dm_entity_type" SET NOT NULL;
ALTER TABLE "public"."entity_log" ALTER COLUMN "dm_entity_id" SET NOT NULL;
ALTER TABLE "public"."entity_log" ALTER COLUMN "username" TYPE varchar(255);
ALTER TABLE "public"."entity_log" ALTER COLUMN "user_source" TYPE varchar(255);
ALTER TABLE "public"."enumeration_value" ALTER COLUMN "enumeration_value" DROP NOT NULL;
ALTER TABLE "public"."folder" ALTER COLUMN "parent_type" SET NOT NULL;
ALTER TABLE "public"."folder" ALTER COLUMN "parent_id" SET NOT NULL;
ALTER TABLE "public"."folder" DROP COLUMN "folder_name" CASCADE;
ALTER TABLE "public"."generic_log" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "public"."generic_log" ALTER COLUMN "log_time" SET NOT NULL;
ALTER TABLE "public"."generic_log" ALTER COLUMN "username" TYPE varchar(255);
ALTER TABLE "public"."generic_log" ALTER COLUMN "user_source" TYPE varchar(255);
ALTER TABLE "public"."generic_log" DROP COLUMN "dm_entity_id" CASCADE;
ALTER TABLE "public"."generic_log" DROP COLUMN "dm_entity_type" CASCADE;
ALTER TABLE "public"."groups" ALTER COLUMN "gid" TYPE varchar(255);
ALTER TABLE "public"."groups" ALTER COLUMN "authentication_source" TYPE varchar(255);
ALTER TABLE "public"."groups" ALTER COLUMN "group_name" TYPE varchar(255);
ALTER TABLE "public"."meta" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "public"."meta" ALTER COLUMN "meta_type" SET NOT NULL;
ALTER TABLE "public"."meta" ALTER COLUMN "meta_name" TYPE varchar(255);
ALTER TABLE "public"."meta_feed" ALTER COLUMN "java_class" SET NOT NULL;
ALTER TABLE "public"."meta_feed" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "public"."meta_feed" ALTER COLUMN "meta_feed_name" TYPE varchar(255),ALTER COLUMN "meta_feed_name" SET NOT NULL;
ALTER TABLE "public"."meta_feed" ADD COLUMN "name" varchar(255);
ALTER TABLE "public"."meta_number_value" ALTER COLUMN "meta_number_value" SET NOT NULL;
ALTER TABLE "public"."meta_string_value" ALTER COLUMN "meta_string_value" TYPE varchar(255);
CREATE TABLE "public"."repositories" ("repository_id" int8 NOT NULL,"repository_default" bool,"repository_name" varchar(255) NOT NULL,"repository_path" varchar(255) NOT NULL,CONSTRAINT "repositories_pkey" PRIMARY KEY ("repository_id") NOT DEFERRABLE INITIALLY IMMEDIATE) WITH (OIDS=FALSE);
ALTER TABLE "public"."roles" ALTER COLUMN "username" TYPE varchar(255);
ALTER TABLE "public"."roles" ALTER COLUMN "user_source" TYPE varchar(255);
ALTER TABLE "public"."rule_exclude_paths" ADD COLUMN "excludepaths" varchar(255);
ALTER TABLE "public"."rule_exclude_paths" DROP COLUMN "excl_path" CASCADE;
ALTER TABLE "public"."rule_param" ALTER COLUMN "param_value" DROP NOT NULL;
ALTER TABLE "public"."rule_param" ALTER COLUMN "param_name" TYPE varchar(255);
ALTER TABLE "public"."rules" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "public"."rules" ALTER COLUMN "java_class" TYPE varchar(255),ALTER COLUMN "java_class" DROP NOT NULL;
ALTER TABLE "public"."rules" ALTER COLUMN "rule_name" TYPE varchar(255),ALTER COLUMN "rule_name" DROP NOT NULL;
ALTER TABLE "public"."rules" ALTER COLUMN "dm_path" TYPE varchar(255),ALTER COLUMN "dm_path" DROP NOT NULL;
ALTER TABLE "public"."rules" ADD COLUMN "rule_creation_date" timestamp(6) NULL;
ALTER TABLE "public"."rules" ADD COLUMN "rule_owner" varchar(255);
ALTER TABLE "public"."rules" ADD COLUMN "rule_owner_source" varchar(255);
ALTER TABLE "public"."rules" ADD COLUMN "rule_update_date" timestamp(6) NULL;
ALTER TABLE "public"."symbolic_link" ADD COLUMN "target_entity_type" int4 NOT NULL;
ALTER TABLE "public"."symbolic_link" ADD COLUMN "target_entity_id" int8 NOT NULL;
ALTER TABLE "public"."symbolic_link" DROP COLUMN "dm_entity_id" CASCADE;
ALTER TABLE "public"."symbolic_link" DROP COLUMN "dm_entity_type" CASCADE;
ALTER TABLE "public"."user_attributes" ALTER COLUMN "user_id" TYPE varchar(255);
ALTER TABLE "public"."user_attributes" ALTER COLUMN "authentication_source" TYPE varchar(255);
ALTER TABLE "public"."user_attributes" ALTER COLUMN "attribute_value" TYPE varchar(255),ALTER COLUMN "attribute_value" DROP NOT NULL;
ALTER TABLE "public"."user_group" ALTER COLUMN "user_id" TYPE varchar(255);
ALTER TABLE "public"."user_group" ALTER COLUMN "authentication_source" TYPE varchar(255);
ALTER TABLE "public"."user_group" ALTER COLUMN "gid" TYPE varchar(255);
ALTER TABLE "public"."user_session" ALTER COLUMN "id" TYPE varchar(255);
ALTER TABLE "public"."user_session" ADD COLUMN "groups" bytea;
ALTER TABLE "public"."user_session" ALTER COLUMN "last_use" TYPE timestamp(6);
ALTER TABLE "public"."user_session" ADD COLUMN "metadatas" varchar(255);
ALTER TABLE "public"."user_session" ALTER COLUMN "user_id" TYPE varchar(255);
ALTER TABLE "public"."user_session" ALTER COLUMN "user_source" TYPE varchar(255);
ALTER TABLE "public"."users" ALTER COLUMN "user_id" TYPE varchar(255);
ALTER TABLE "public"."users" ALTER COLUMN "authentication_source" TYPE varchar(255);
ALTER TABLE "public"."users" ALTER COLUMN "user_fullname" TYPE varchar(255);
ALTER TABLE "public"."users" ALTER COLUMN "mail" TYPE varchar(255);
ALTER TABLE "public"."users" ALTER COLUMN "user_password" TYPE varchar(255);
ALTER TABLE "public"."workflow" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "public"."workflow" ALTER COLUMN "workflow_description" TYPE varchar(5000);
ALTER TABLE "public"."workflow" ALTER COLUMN "workflow_name" TYPE varchar(200),ALTER COLUMN "workflow_name" SET NOT NULL;
ALTER TABLE "public"."workflow_status" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "public"."workflow_status" ALTER COLUMN "status_name" TYPE varchar(200),ALTER COLUMN "status_name" SET NOT NULL;
ALTER TABLE "public"."workflow_status" ALTER COLUMN "workflow_id" SET NOT NULL;
ALTER TABLE "public"."workflow_status_manager" ALTER COLUMN "security_entity_name" TYPE varchar(255);
ALTER TABLE "public"."workflow_status_manager" ALTER COLUMN "security_entity_source" TYPE varchar(255);
ALTER TABLE "public"."authentication_params" ADD CONSTRAINT "authentication_params_pkey" PRIMARY KEY ("authentication_source_name", "param_name");
ALTER TABLE "public"."authentication_source" ADD CONSTRAINT "authentication_source_pkey" PRIMARY KEY ("source_name");
ALTER TABLE "public"."bookmarks" ADD CONSTRAINT "bookmarks_pkey" PRIMARY KEY ("bk_owner", "bk_owner_source", "dm_entity_id");
ALTER TABLE "public"."checkout" ADD CONSTRAINT "checkout_pkey" PRIMARY KEY ("document_id");
ALTER TABLE "public"."data_transaction" ADD CONSTRAINT "data_transaction_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."dm_entity" ADD CONSTRAINT "dm_entity_pkey" PRIMARY KEY ("dm_entity_id");
ALTER TABLE "public"."dm_entity" ADD CONSTRAINT "dm_entity_dm_entity_path_key" UNIQUE ("dm_entity_path");
ALTER TABLE "public"."dm_entity_acl" ADD CONSTRAINT "dm_entity_acl_pkey" PRIMARY KEY ("dm_entity_id", "rule_hash");
ALTER TABLE "public"."dm_entity_attributes" ADD CONSTRAINT "dm_entity_attributes_pkey" PRIMARY KEY ("dm_entity_id", "attribute_name");
ALTER TABLE "public"."dm_security_rules" ADD CONSTRAINT "dm_security_rules_pkey" PRIMARY KEY ("security_entity_type", "security_entity_id", "security_entity_source", "rule_hash");
ALTER TABLE "public"."document" ADD CONSTRAINT "document_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."document_comment" ADD CONSTRAINT "document_comment_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."document_type" ADD CONSTRAINT "document_type_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."document_version" ADD CONSTRAINT "document_version_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."document_version" ADD CONSTRAINT "document_version_storage_path_key" UNIQUE ("storage_path");
ALTER TABLE "public"."document_workflow_status" ADD CONSTRAINT "document_workflow_status_pkey" PRIMARY KEY ("document_id", "workflow_status_id");
ALTER TABLE "public"."document_workflow_status_request" ADD CONSTRAINT "document_workflow_status_request_pkey" PRIMARY KEY ("username", "user_source", "document_id", "workflow_status_id", "request_date");
ALTER TABLE "public"."entity_log" ADD CONSTRAINT "entity_log_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."enumeration_value" ADD CONSTRAINT "enumeration_value_enumeration_id_enumeration_value_key" UNIQUE ("enumeration_id", "enumeration_value");
ALTER TABLE "public"."folder" ADD CONSTRAINT "folder_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."generic_log" ADD CONSTRAINT "generic_log_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."groups" ADD CONSTRAINT "groups_pkey" PRIMARY KEY ("gid", "authentication_source");
ALTER TABLE "public"."meta" ADD CONSTRAINT "meta_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."meta_boolean_value" ADD CONSTRAINT "meta_boolean_value_pkey" PRIMARY KEY ("document_version_id", "meta_id");
ALTER TABLE "public"."meta_date_value" ADD CONSTRAINT "meta_date_value_pkey" PRIMARY KEY ("document_version_id", "meta_id");
ALTER TABLE "public"."meta_feed" ADD CONSTRAINT "meta_feed_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."meta_number_value" ADD CONSTRAINT "meta_number_value_pkey" PRIMARY KEY ("document_version_id", "meta_id");
ALTER TABLE "public"."meta_string_value" ADD CONSTRAINT "meta_string_value_pkey" PRIMARY KEY ("document_version_id", "meta_id");
ALTER TABLE "public"."related_documents" ADD CONSTRAINT "related_documents_pkey" PRIMARY KEY ("document_id", "related_document_id");
ALTER TABLE "public"."roles" ADD CONSTRAINT "roles_pkey" PRIMARY KEY ("role_value", "username", "user_source");
ALTER TABLE "public"."rule_event" ADD CONSTRAINT "rule_event_pkey" PRIMARY KEY ("rule_id", "event_name", "event_status");
ALTER TABLE "public"."rule_param" ADD CONSTRAINT "rule_param_pkey" PRIMARY KEY ("rule_id", "param_name");
ALTER TABLE "public"."rules" ADD CONSTRAINT "rules_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."symbolic_link" ADD CONSTRAINT "symbolic_link_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."user_attributes" ADD CONSTRAINT "user_attributes_pkey" PRIMARY KEY ("user_id", "authentication_source", "attribute_name");
ALTER TABLE "public"."user_group" ADD CONSTRAINT "user_group_pkey" PRIMARY KEY ("user_id", "gid", "authentication_source");
ALTER TABLE "public"."user_session" ADD CONSTRAINT "user_session_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("user_id", "authentication_source");
ALTER TABLE "public"."workflow" ADD CONSTRAINT "workflow_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."workflow_status" ADD CONSTRAINT "workflow_status_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."workflow_status_manager" ADD CONSTRAINT "workflow_status_manager_pkey" PRIMARY KEY ("security_entity_name", "security_entity_source", "security_entity_type", "workflow_status_id");
ALTER TABLE "public"."workspace" ADD CONSTRAINT "workspace_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."authentication_params" ADD CONSTRAINT "fkedbddd2d3b92fe3" FOREIGN KEY ("authentication_source_name") REFERENCES "public"."authentication_source" ("source_name") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."checkout" ADD CONSTRAINT "fk5b9b4d4647c840a9" FOREIGN KEY ("document_id") REFERENCES "public"."document" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."data_transaction" ADD CONSTRAINT "fk3bcff1c9645bfb14" FOREIGN KEY ("document_version_id") REFERENCES "public"."document_version" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."dm_entity_acl" ADD CONSTRAINT "fk5a502ba423c101fc" FOREIGN KEY ("dm_entity_id") REFERENCES "public"."dm_entity" ("dm_entity_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."dm_entity_attributes" ADD CONSTRAINT "fk295e24fd23c101fc" FOREIGN KEY ("dm_entity_id") REFERENCES "public"."dm_entity" ("dm_entity_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."document" ADD CONSTRAINT "fk335cd11b41df8056" FOREIGN KEY ("id") REFERENCES "public"."dm_entity" ("dm_entity_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."document" ADD CONSTRAINT "fk335cd11b480389" FOREIGN KEY ("folder_id") REFERENCES "public"."folder" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."document_comment" ADD CONSTRAINT "fk5e691b3b645bfb14" FOREIGN KEY ("document_version_id") REFERENCES "public"."document_version" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."document_type" ADD CONSTRAINT "fk5e81efdef4640560" FOREIGN KEY ("document_type_id") REFERENCES "public"."document_type" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."document_version" ADD CONSTRAINT "fk3ab849b447c840a9" FOREIGN KEY ("document_id") REFERENCES "public"."document" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."document_version" ADD CONSTRAINT "fk3ab849b4f4640560" FOREIGN KEY ("document_type_id") REFERENCES "public"."document_type" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."document_workflow_status" ADD CONSTRAINT "fk6419214e47c840a9" FOREIGN KEY ("document_id") REFERENCES "public"."document" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."document_workflow_status" ADD CONSTRAINT "fk6419214e6344e28" FOREIGN KEY ("workflow_status_id") REFERENCES "public"."workflow_status" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."document_workflow_status_request" ADD CONSTRAINT "fk8208c9e47c840a9" FOREIGN KEY ("document_id") REFERENCES "public"."document" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."document_workflow_status_request" ADD CONSTRAINT "fk8208c9e6344e28" FOREIGN KEY ("workflow_status_id") REFERENCES "public"."workflow_status" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."enumeration_value" ADD CONSTRAINT "fkdd8eed79a44da6d9" FOREIGN KEY ("enumeration_id") REFERENCES "public"."meta_feed" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."folder" ADD CONSTRAINT "fkb45d1c6e41df8056" FOREIGN KEY ("parent_id") REFERENCES "public"."dm_entity" ("dm_entity_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."folder" ADD CONSTRAINT "fkb45d1c6ebd46240b" FOREIGN KEY ("id") REFERENCES "public"."dm_entity" ("dm_entity_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."meta" ADD CONSTRAINT "fk331605f4640560" FOREIGN KEY ("document_type_id") REFERENCES "public"."document_type" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."meta" ADD CONSTRAINT "fk3316056c37b274" FOREIGN KEY ("meta_feed_id") REFERENCES "public"."meta_feed" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."meta_boolean_value" ADD CONSTRAINT "fk17ba281c645bfb141a081de0" FOREIGN KEY ("document_version_id") REFERENCES "public"."document_version" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."meta_boolean_value" ADD CONSTRAINT "fk17ba281c7eb6dfe91a081de0" FOREIGN KEY ("meta_id") REFERENCES "public"."meta" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."meta_date_value" ADD CONSTRAINT "fk17ba281c645bfb14d1bea41a" FOREIGN KEY ("document_version_id") REFERENCES "public"."document_version" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."meta_date_value" ADD CONSTRAINT "fk17ba281c7eb6dfe9d1bea41a" FOREIGN KEY ("meta_id") REFERENCES "public"."meta" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."meta_number_value" ADD CONSTRAINT "fk17ba281c645bfb14796d78f5" FOREIGN KEY ("document_version_id") REFERENCES "public"."document_version" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."meta_number_value" ADD CONSTRAINT "fk17ba281c7eb6dfe9796d78f5" FOREIGN KEY ("meta_id") REFERENCES "public"."meta" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."meta_string_value" ADD CONSTRAINT "fk17ba281c645bfb143f5547bd" FOREIGN KEY ("document_version_id") REFERENCES "public"."document_version" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."meta_string_value" ADD CONSTRAINT "fk17ba281c7eb6dfe93f5547bd" FOREIGN KEY ("meta_id") REFERENCES "public"."meta" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."related_documents" ADD CONSTRAINT "fk8d14efa447c840a9" FOREIGN KEY ("document_id") REFERENCES "public"."document" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."related_documents" ADD CONSTRAINT "fk8d14efa4c52c5295" FOREIGN KEY ("related_document_id") REFERENCES "public"."document" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."rule_event" ADD CONSTRAINT "fke5b23f97566b82cc" FOREIGN KEY ("rule_id") REFERENCES "public"."rules" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."rule_exclude_paths" ADD CONSTRAINT "fkbeb9646566b82cc" FOREIGN KEY ("rule_id") REFERENCES "public"."rules" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."rule_param" ADD CONSTRAINT "fke643e58a566b82cc" FOREIGN KEY ("rule_id") REFERENCES "public"."rules" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."symbolic_link" ADD CONSTRAINT "fk2ec70b6741df8056" FOREIGN KEY ("target_entity_id") REFERENCES "public"."dm_entity" ("dm_entity_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."symbolic_link" ADD CONSTRAINT "fk2ec70b67bd46240b" FOREIGN KEY ("id") REFERENCES "public"."dm_entity" ("dm_entity_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."symbolic_link" ADD CONSTRAINT "fk2ec70b67b6abd04" FOREIGN KEY ("parent_id") REFERENCES "public"."dm_entity" ("dm_entity_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."user_attributes" ADD CONSTRAINT "fk67c2564b33609d94" FOREIGN KEY ("user_id", "authentication_source") REFERENCES "public"."users" ("user_id", "authentication_source") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."user_group" ADD CONSTRAINT "fk72a9010bbaa9590b" FOREIGN KEY ("gid","authentication_source") REFERENCES "public"."groups" ("gid", "authentication_source") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."user_group" ADD CONSTRAINT "fk72a9010b33609d94" FOREIGN KEY ("user_id", "authentication_source") REFERENCES "public"."users" ("user_id", "authentication_source") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."workflow_status" ADD CONSTRAINT "fk837290725e6d0e29" FOREIGN KEY ("successor_id") REFERENCES "public"."workflow_status" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."workflow_status" ADD CONSTRAINT "fk837290722f3e58f4" FOREIGN KEY ("workflow_id") REFERENCES "public"."workflow" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."workflow_status_manager" ADD CONSTRAINT "fk34b4b4e06344e28" FOREIGN KEY ("workflow_status_id") REFERENCES "public"."workflow_status" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."workspace" ADD CONSTRAINT "fk4217ec9541df8056" FOREIGN KEY ("id") REFERENCES "public"."dm_entity" ("dm_entity_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
